= TelloSimulator

Der TelloSimulator ermöglicht das Experimentieren und Debuggen mit einer virtuellen Tello Drohne. Die Applikation
bietet die Programmierschnittstelle des Tello SDK 2.0 an, sendet und empfängt UDP-Pakete analog zur echten Drohne
und verfügt über ein UI mit 3D-Welt, in welcher die virtuelle Drohne fliegt.

== Installationsanleitung:

Eine detaillierte Installationsanleitung ist im link:SETUP.adoc[SETUP.adoc] zu finden.

Um den Simulator zu testen, wird zusätzlich ein Operator-Programm benötigt, welches die Tello-Drohne und somit auch den Simulator ansteuern kann. Für Testzwecke steht hierzu unter
https://github.com/danielobrist/TelloDemoCommander eine Demo-Applikation zur Verfügung.


== Operator-Programm mit der Simulator-API verbinden:

//TODO: Anforderungsänderung "muss im WLAN funktionieren" --> TelloSDKValues / Verbindung mit anderen IPs erklären
Die Verbindung mit dem Simulator ist sehr ähnlich wie mit der echten Drohne. Allerdings gibt es systembedingt ein paar Unterschiede. Falls der Simulator auf dem gleichen Gerät wie der Operator läuft, verwendet er
die localhost Loopback-Addresse 127.0.0.1, wodurch nicht dieselben Ports genutzt werden können wie mit der echten Drohne.
Folgende Anpassungen im *Operator-Programm* sind deshalb für den Verbindungsaufbau zum Simulator nötig:

*Schritt 1:* Port des DatagramSockets von *8889* (Default Tello Command Port) auf *8879* (Simulator Command Port) umstellen.

`ds = new DatagramSocket(8879);`

*Schritt 2:*

(Falls der Simulator auf dem gleichen Gerät wie der Operator läuft):

Statt auf *192.168.10.1* (Tello Drohne IP) auf *127.0.0.1* (localhost) verbinden.

`ds.connect(127.0.0.1);`

(Falls der Simulator auf einem anderen Gerät wie der Operator läuft):

Statt auf *192.168.10.1* (Tello Drohne IP) auf *<IP-Adresse des Simulators>* verbinden. (Aktuelle IP ersichtlich im Simulator UI)

`ds.connect(<IP-Adresse des Simulators>);`


*Schritt 3:* //TODO: Tello State und Video Stream Sockets im Simulator umsetzen und API hier dokumentieren


Eine detailliere Dokumentation

== Literaturverzeichnis
//TODO:
JavaFX 3D Tutorial: https://www.youtube.com/watch?v=nBjwBmH8OhQ

---
