= TelloSimulator

:imagesdir: assets

link:README.adoc[Deutsch]

The TelloSimulator allows experimenting and debugging with a virtual Tello drone. The application
offers the programming interface of the Tello SDK 2.0, sends and receives UDP packets analogous to the real drone
and has a UI with a 3D world in which the virtual drone flies.

== Installation instructions:

Clone the repository and run the Gradle project with:

[source,bash]
 ./gradlew run

or

[source,bash]
 gradlew run

For detailed installation instructions, including IntelliJ IDEA setup, please refer to the link:SETUP.adoc[SETUP.adoc].

To use the simulator, an operator program, which can control the Tello drone and thus also the simulator, is required. For test purposes there is a demo application avaliable under
https://github.com/danielobrist/TelloDemoCommander.

== Simulator-API:

The connection with the simulator is very similar to the real drone. However, there are a few differences due to the system.
The following sections document the simulator API and give exemplary Java code for establishing the connection.

=== Sending commands  & receiving responses

. Create a command socket on port *8889* to send commands:
[source,java]
ds = new DatagramSocket(8889);

. Connection to simulator IP to receive command responses from the simulator:
.. *Variant 1: Simulator & operator on the same device:*
Connect to the *loopback IP* on port *8879*:
[source,java]
ds.connect(InetAddress.getLoopbackAddress(), 8879)

.. *Variant 2: Simulator & operator on different devices:*
Connect to the *IP of the simulator* (visible in the simulator UI) on port *8879*:
[source,java]
ds.connect(InetAddress.getByName(simulatorIP), 8879)

. Send and receive UDP packets:

[source,java]
DatagramPacket packet = new DatagramPacket(...);

[source,java]
ds.send(packet);

[source,java]
ds.receive(packet);


=== Receive state

. Create a state socket on port *8890* to receive state from the simulator:

[source,java]
ds = new DatagramSocket(8890, InetAddress.getByName("0.0.0.0"));

. Receive state packets:

[source,java]
ds.receive(packet);

The state is sent every 10 ms. It is sent to the address, where the *first command* was received from.

=== Receive video

The current version of TelloSimulator does not yet send a video stream.

== References


---
