:icons: font
:stem:
:imagesdir: assets
:experimental:

= TelloSimulator

Der TelloSimulator ermöglicht das Experimentieren und Debuggen mit einer virtuellen Tello Drohne. Die Applikation
bietet die Programmierschnittstelle des Tello SDK 2.0 an, sendet und empfängt UDP-Pakete analog zur echten Drohne
und verfügt über ein UI mit 3D-Welt, in welcher die virtuelle Drohne fliegt.

== Installationsanleitung:

Repository klonen und das Gradle-Project starten mit:
[source,bash]
....
./gradlew run
....
oder

[source,bash]
....
gradlew run
....

TIP: Eine detailliertere Installationsanleitung, inkl. IntelliJ IDEA Setup, ist im link:/docs/SETUP.adoc[SETUP.adoc] zu finden.

NOTE: Um den Simulator zu verwenden, wird zusätzlich ein Operator-Programm benötigt, welches die Tello-Drohne und
somit auch den Simulator ansteuern kann. Falls kein eigener Client verfügbar ist, steht
https://github.com/danielobrist/TelloDemoCommander[hier] eine Demo-Applikation zur Verfügung.


== Simulator-API:

Die Verbindung mit dem Simulator ist sehr ähnlich wie mit der echten Drohne. Allerdings gibt es systembedingt ein paar Unterschiede.
Die nachfolgenden Abschnitte dokumentieren die Simulator-API und geben beispielhaften Java-Code zum Verbindungsaufbau.

=== Commands senden & Responses empfangen

. Command-Socket mit bind zu Port *8889* erstellen, um Responses zu empfangen:
[source,java]
ds = new DatagramSocket(8889);

. Connection zur Simulator-IP (sichtbar im Simulator-UI) auf Port *8879*, um Commands an den Simulator zu schicken:
[source,java]
ds.connect(InetAddress.getByName(simulatorIP), 8879)

. UDP-Pakete senden und empfangen:
[source,java]
DatagramPacket packet = new DatagramPacket(...);
ds.send(packet);
ds.receive(packet);

=== State empfangen

. State-Socket auf Port *8890* erstellen, um State vom Simulator zu empfangen:
[source,java]
ds = new DatagramSocket(8890);

. State-Pakete empfangen:
[source,java]
ds.receive(packet);

NOTE: Der State wird alle 100 ms versendet. Er wird an die Adresse geschickt, von der *das erste command* empfangen wurde.

=== Video empfangen

WARNING: Der TelloSimulator versendet in der aktuellen Version noch keinen Videostream.


== Simulator UI
//TODO: Screenshot und ein paar basic Erklärungen zum Simulator User Interface

|===
|Key |Purpose

|kbd:[LeftMouse]
|Rotate Drone Camera

|kbd:[Ctrl+LeftMouse]
|Rotate Drone Camera slowly

|kbd:[Shift+LeftMouse]
|Rotate Drone Camera fast

|kbd:[RightMouse]
|Move Drone Camera

|kbd:[Ctrl+LeftMouse]
|Move Drone Camera slowly

|kbd:[Shift+LeftMouse]
|Move Drone Camera fast

|kbd:[Scroll]
|Increase/Decrease zoom

|kbd:[Ctrl+Scroll]
|Increase/Decrease zoom slowly
|===

'''

.Mehr Informationen
****
Dieses Projekt wurde im Rahmen des IP5-Projekts im Studiengang Informatik mit Vertiefung in Design und Management an
der Fachhochschule Nordwestschweiz FHNW entwickelt. Eine ausführliche Dokumentation ist im link:/docs/BERICHT.adoc[Bericht]
zu finden.
****
