= TelloSimulator

:imagesdir: assets

link:README.en.adoc[English Version]

Der TelloSimulator ermöglicht das Experimentieren und Debuggen mit einer virtuellen Tello Drohne. Die Applikation
bietet die Programmierschnittstelle des Tello SDK 2.0 an, sendet und empfängt UDP-Pakete analog zur echten Drohne
und verfügt über ein UI mit 3D-Welt, in welcher die virtuelle Drohne fliegt. Eine ausführliche Dokumentation zu diesem
Projekt ist im link:BERICHT.adoc[Bericht] zu finden.

== Installationsanleitung:

Repository klonen und das Gradle-Project starten mit:
[source,bash]
....
./gradlew run
....
oder

[source,bash]
....
gradlew run
....
TIP: Eine detailliertere Installationsanleitung, inkl. IntelliJ IDEA Setup, ist im link:SETUP.adoc[SETUP.adoc] zu finden.

NOTE: Um den Simulator zu verwenden, wird zusätzlich ein Operator-Programm benötigt, welches die Tello-Drohne und
somit auch den Simulator ansteuern kann. Für Testzwecke steht hierzu unterhttps://github.com/danielobrist/TelloDemoCommander eine Demo-Applikation zur Verfügung.

== Simulator-API:

Die Verbindung mit dem Simulator ist sehr ähnlich wie mit der echten Drohne. Allerdings gibt es systembedingt ein paar Unterschiede.
Die nachfolgenden Abschnitte dokumentieren die Simulator-API und geben beispielhaften Java-Code zum Verbindungsaufbau.

=== Commands senden & Responses empfangen

. Command-Socket auf Port *8889* erstellen, um Commands zu senden:
[source,java]
ds = new DatagramSocket(8889);

. Connection zur Simulator-IP, um Command-Responses vom Simulator zu empfangen:
** *Variante 1: Simulator & Operator auf gleichem Gerät:* Connection zur *Loopback-IP* auf Port *8879* herstellen:
[source,java]
ds.connect(InetAddress.getLoopbackAddress(), 8879)

** *Variante 2: Simulator & Operator auf verschiedenen Geräten:*
Connection zur *IP des Simulators* (sichtbar im Simulator-UI) auf Port *8879* herstellen:
[source,java]
ds.connect(InetAddress.getByName(simulatorIP), 8879)

. UDP-Pakete senden und empfangen:
[source,java]
DatagramPacket packet = new DatagramPacket(...);

 ds.send(packet);

 ds.receive(packet);


=== State empfangen

. State-Socket auf Port *8890* erstellen, um State vom Simulator zu empfangen:
[source,java]
ds = new DatagramSocket(8890, InetAddress.getByName("0.0.0.0"));

. State-Pakete empfangen:
[source,java]
ds.receive(packet);

NOTE: Der State wird alle 10 ms versendet. Er wird an die Adresse geschickt, von der *das erste command* empfangen wurde.

=== Video empfangen

WARNING: Der TelloSimulator versendet in der aktuellen Version noch keinen Videostream.

== Literaturverzeichnis


---
